server:
  port: 8087
  servlet:
    context-path: '/ead-course/'

spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/ead-course
    username: postgres
    password: 586910
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
